analyze table part delete statistics;
analyze table supplier delete statistics;
analyze table partsupp delete statistics;
analyze table customer delete statistics;
analyze table orders delete statistics;
analyze table lineitem delete statistics;
analyze table nation delete statistics;
analyze table region delete statistics;
alter table part inmemory;
alter table supplier inmemory;
alter table partsupp inmemory;
alter table customer inmemory;
alter table orders inmemory;
alter table lineitem inmemory;
alter table nation inmemory;
alter table region inmemory;
alter table part parallel 4;
alter table supplier parallel 4;
alter table partsupp parallel 4;
alter table customer parallel 4;
alter table orders parallel 4;
alter table lineitem parallel 4;
alter table nation parallel 4;
alter table region parallel 4;