analyze table part compute statistics;
analyze table supplier compute statistics;
analyze table partsupp compute statistics;
analyze table customer compute statistics;
analyze table orders compute statistics;
analyze table lineitem compute statistics;
analyze table nation compute statistics;
analyze table region compute statistics;
alter table part inmemory;
alter table supplier inmemory;
alter table partsupp inmemory;
alter table customer inmemory;
alter table orders inmemory;
alter table lineitem inmemory;
alter table nation inmemory;
alter table region inmemory;
alter table part parallel 1;
alter table supplier parallel 1;
alter table partsupp parallel 1;
alter table customer parallel 1;
alter table orders parallel 1;
alter table lineitem parallel 1;
alter table nation parallel 1;
alter table region parallel 1;